default_stages: [pre-commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        types_or: [python]
      - id: trailing-whitespace
        types_or: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python]
      - id: ruff-format
        types_or: [python]

  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.32.0'
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
