name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Ruff Linter
        run: poetry run ruff check .

      - name: Run Ruff Formatter
        run: poetry run ruff format --diff

      - name: MyPy static type checker
        run: poetry run mypy src/

      - name: Run Vulture checker
        run: poetry run vulture src/ --min-confidence 90

      - name: Run Xenon checker
        run: poetry run xenon src/

      - name: Lizard report
        run: poetry run lizard -l python --output_file lizard-report.html src/

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: |
          poetry run pytest

      - name: Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7
          overwrite: true
